{
 "title": "MSI Afterburner Reptar",
 "description": "Shows stats from MSI Afterburner",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "graphite", "label": "Graphite", "query": "graphite" },
   {
    "name": "afterburner",
    "label": "CollectD Metric Prefix",
    "query": "collectd.*.curl-xml-afterburner"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($afterburner.gauge-CPU_usage, 'Intel Core i5-6600K')"
    },
    {
     "target": "alias($afterburner.gauge-GPU_usage, 'Radeon R9 390 8GB')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($afterburner.gauge-Framerate, 'FPS')"
    },
    {
     "target": "alias($afterburner.gauge-Frametime, 'Frametime ')"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($afterburner.gauge-CPU_temperature, 'CPU')"
    },
    {
     "target": "alias($afterburner.gauge-GPU_temperature, 'GPU')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($afterburner.gauge-RAM_usage, 'RAM')"
    },
    {
     "target": "alias($afterburner.gauge-Memory_usage, 'VRAM')"
    }
   ]
  },
  {
   "title": "Clockspeeds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "alias(scale($afterburner.gauge-CPU_clock, 1000000), 'CPU')"
    },
    {
     "target": "alias(scale($afterburner.gauge-Core_clock, 1000000), 'GPU')"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "target": "alias($afterburner.gauge-CPU_power, 'CPU')"
    },
    {
     "target": "alias($afterburner.gauge-Power, 'GPU')"
    }
   ]
  },
  {
   "title": "Voltage / Memory Clock",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "alias(scale($afterburner.gauge-Memory_clock, 1000000), 'GPU Memory Clock')"
    },
    {
     "target": "alias($afterburner.gauge-GPU_voltage, 'Voltage')"
    }
   ]
  },
  {
   "title": "GPU Fans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias($afterburner.gauge-Fan_speed, 'Fan 1 Speed')"
    },
    {
     "target": "alias($afterburner.gauge-Fan_speed_2, 'Fan 2 Speed')"
    },
    {
     "target": "alias($afterburner.gauge-Fan_tachometer, 'Fan 1 rpm')"
    },
    {
     "target": "alias($afterburner.gauge-Fan_tachometer_2, 'Fan 2 rpm')"
    }
   ]
  },
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 } }
 ]
}